### ISSUE TITLE
I don’t understand how the error is thrown when I find that next is called repeatedly.

### ISSUE THREAD

**Issue by ljybill** [koajs/compose#112]
Hi, I am learning source code about koa.I'm sorry, my English is not good.

https://github.com/koajs/compose/blob/25568a36509fefc58914bc2a7600f787b16aa0df/index.js#L36

I don’t understand how the error is thrown when I find that next is called repeatedly.

Below is my test code

``` javascript
const Koa = require('koa');

const app = new Koa();

app.use(
    async function (ctx, next) {
        try {
            await next();
        } catch (e) {
            console.log('catch error:', e.toString())
        }
    }
)

app.use(
    function (ctx, next) {
        console.log('m1');
        next();
        next();
    }
)

app.use(
    function (ctx, next) {
        console.log('m2');
        next();
        next();
    }
)

app.listen(3000);
```

The console will print a log when I trigger it
``` log
m1
m2
(node:15374) UnhandledPromiseRejectionWarning: Error: next() called multiple times
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:36:45)
    at /Users/helloWorld/code/learn-koa/playground/main.js:27:9
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:42:32)
    at /Users/helloWorld/code/learn-koa/playground/main.js:18:9
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:42:32)
    at /Users/helloWorld/code/learn-koa/playground/main.js:8:19
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:42:32)
    at /Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:34:12
    at Application.handleRequest (/Users/helloWorld/code/learn-koa/playground/node_modules/koa/lib/application.js:168:12)
    at Server.handleRequest (/Users/helloWorld/code/learn-koa/playground/node_modules/koa/lib/application.js:150:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15374) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15374) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15374) UnhandledPromiseRejectionWarning: Error: next() called multiple times
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:36:45)
    at /Users/helloWorld/code/learn-koa/playground/main.js:19:9
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:42:32)
    at /Users/helloWorld/code/learn-koa/playground/main.js:8:19
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:42:32)
    at /Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:34:12
    at Application.handleRequest (/Users/helloWorld/code/learn-koa/playground/node_modules/koa/lib/application.js:168:12)
    at Server.handleRequest (/Users/helloWorld/code/learn-koa/playground/node_modules/koa/lib/application.js:150:19)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
(node:15374) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
m1
m2
(node:15374) UnhandledPromiseRejectionWarning: Error: next() called multiple times
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:36:45)
    at /Users/helloWorld/code/learn-koa/playground/main.js:27:9
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:42:32)
    at /Users/helloWorld/code/learn-koa/playground/main.js:18:9
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:42:32)
    at /Users/helloWorld/code/learn-koa/playground/main.js:8:19
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:42:32)
    at /Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:34:12
    at Application.handleRequest (/Users/helloWorld/code/learn-koa/playground/node_modules/koa/lib/application.js:168:12)
    at Server.handleRequest (/Users/helloWorld/code/learn-koa/playground/node_modules/koa/lib/application.js:150:19)
(node:15374) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:15374) UnhandledPromiseRejectionWarning: Error: next() called multiple times
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:36:45)
    at /Users/helloWorld/code/learn-koa/playground/main.js:19:9
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:42:32)
    at /Users/helloWorld/code/learn-koa/playground/main.js:8:19
    at dispatch (/Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:42:32)
    at /Users/helloWorld/code/learn-koa/playground/node_modules/koa-compose/index.js:34:12
    at Application.handleRequest (/Users/helloWorld/code/learn-koa/playground/node_modules/koa/lib/application.js:168:12)
    at Server.handleRequest (/Users/helloWorld/code/learn-koa/playground/node_modules/koa/lib/application.js:150:19)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
(node:15374) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

If I change the function to asynchronous call, the error can be caught

``` javascript
const Koa = require('koa');

const app = new Koa();

app.use(
    async function (ctx, next) {
        try {
            await next();
        } catch (e) {
            console.log('catch error:', e.toString())
        }
    }
)

app.use(
    async function (ctx, next) {
        console.log('m1');
        await next();
        await next();
    }
)

app.use(
    async function (ctx, next) {
        console.log('m2');
        await next();
        await next();
    }
)

app.listen(3000);
```

Is it necessary to use asynchronous function？

**Comment by miwnwski** [comment]
When you call `next` without `await` you're actually producing a hidden bug. You need to return the promise for it to behave correctly in this context. Try the following:

```js
const Koa = require('koa');

const app = new Koa();

app.use(
    async function (ctx, next) {
        try {
            await next();
        } catch (e) {
            console.log('catch error:', e.toString())
        }
    }
)

app.use(
    function (ctx, next) {
        console.log('m1');
        return next()
    }
)

app.use(
    function (ctx, next) {
        console.log('m2');
        return next().then(next)
    }
)

app.listen(3000);
```

If you don't return the promise it is ran out of context.

Just a small disclaimer, you shouldn't be doing this in "real" applications. I understand this is an exercise which is totally fine.

**Comment by ljybill** [comment]
Thank you very much. I get it!
